name: Tests (PHP)

on:
  push:
    branches:
      - 'master'
  pull_request:
    paths:
      - '**.php'
      - '.php_cs'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: composer install

      - name: PHPUnit @ PHP 7.4
        uses: php-actions/phpunit@v2
        with:
          php_version: 7.4

      - name: PHPUnit @ PHP 8
        uses: php-actions/phpunit@v2
        with:
          php_version: latest
